---
title: "mp3"
author: "Christine Chu"
date: "April 4, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)  
library(tidyverse)
library(sf)
library(macleish)
library(leaflet)  # HTML widgit, use javascript library D3.js
library(RSQLite)
library(lwgeom) 
```

Emily
```{r}
forest_pal <- colorFactor("Set1",macleish_layers[["forests"]]$Sheet1__Na)

base_plot <- leaflet() %>%
  addTiles() %>%
  addPolygons(data = macleish_layers[["buildings"]]) %>%
  addPolylines(data = macleish_layers[["streams"]], weight =1, color="Blue") %>%
  addPolylines(data = macleish_layers[["trails"]], weight =1, color="Brown") %>%
  addCircleMarkers(data=macleish_layers[["challenge_courses"]], color="Green", weight=.1) %>%
  addPolygons(data = macleish_layers[["research"]]) %>%
  addPolygons(data = macleish_layers[["forests"]], 
              color = ~forest_pal(Sheet1__Na), weight = 0.1, 
              fillOpacity = 1,
              popup = ~ Sheet1__Na, group = "Natural") %>%
  addMarkers(lng = -72.680, lat = 42.448, data = macleish_layers,
             popup = "Parking?") 

base_plot 
```


```{r}
stream_buffer <- macleish_layers[["streams"]] %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist=10) %>%
  st_transform(4326)

stream_buff <- leaflet() %>%
  addTiles() %>%
  addPolylines(data=macleish_layers[["streams"]], weight=1, color="black") %>%
  addPolygons(data = stream_buffer)
```

```{r} 
base_plot %>%
  addPolygons(data=stream_buff)
  ####some kind of overlay function 
```



Parking lot (in theory is at this location, so we could ad a thumb tack then put in a centrioid/buffer for intersection purposes:
lat:   42°26'52.81"N
lon:  72°40'50.46"W

Camping sites:  

Group Campsite (42.450976, -72.678154)
Remote Campite (42.458570, -72.674732)


Christine
```{r}

proj4_aea <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=37.5 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

#area is in meters
base_plot <- leaflet() %>%
  addTiles() %>%
  addPolygons(data = macleish_layers[["buildings"]]) %>%
  addPolylines(data = macleish_layers[["streams"]], weight =1, color="Blue") %>%
  addPolylines(data = macleish_layers[["trails"]], weight =1, color="Brown") %>%
  addCircleMarkers(data=macleish_layers[["challenge_courses"]], color="Green", weight=.1) %>% 
  addPolygons(data = macleish_layers[["research"]]) %>%
  addMarkers(lng = -72.68068, lat = 42.448, data = macleish_layers,
             popup = "Parking?")

base_plot 

```

at least 500’ from any research area or any element of the Challenge Course.
```{r}
research_buffer <- macleish_layers[["research"]] %>%
  st_transform(proj4_aea) %>%
  st_buffer(dist= 152) %>%
  st_transform(4326)

#plotting the research buffers 

leaflet() %>%
  addTiles() %>%
  addPolylines(data=macleish_layers[["streams"]], weight=1, color="black") %>%
  addPolygons(data = stream_buffer) %>%
  addPolygons(data=macleish_layers[["research"]], weight=1, color="red") %>%
  addPolygons(data = research_buffer)

```










Dardalie
```{r}
hi
```























